"""empty message

Revision ID: 744b8fe72c5b
Revises: 
Create Date: 2023-11-03 20:29:27.348453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744b8fe72c5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocorrencias',
    sa.Column('id_ocr', sa.Integer(), nullable=False),
    sa.Column('nome_ocorrencia', sa.String(length=150), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_ocr')
    )
    op.create_table('pagamentos',
    sa.Column('id_pag', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_pag')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('permissao', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('name_cliente', sa.String(length=255), nullable=True),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('bairro', sa.String(length=150), nullable=True),
    sa.Column('cidade', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('mensalidade', sa.Float(), nullable=True),
    sa.Column('ocorrencias', sa.Integer(), nullable=True),
    sa.Column('pagamento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ocorrencias'], ['ocorrencias.id_ocr'], ),
    sa.ForeignKeyConstraint(['pagamento'], ['pagamentos.id_pag'], ),
    sa.PrimaryKeyConstraint('id_client')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    op.drop_table('usuarios')
    op.drop_table('pagamentos')
    op.drop_table('ocorrencias')
    # ### end Alembic commands ###
